version: '3.1'

services:
  db:
    image: mysql:8.0.35
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: alswp
      MYSQL_USER: mj
      MYSQL_PASSWORD: alswp
      MYSQL_DATABASE: test
    ports:
      - '3307:3306'
